django_classbaseviews/A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first.urls')),
    path('accounts/', include('accounts.urls')),
]

django_classbaseviews/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views#path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
from .views import(
        PasswordConfirm, UserPassReset, UserLogin,
        PasswordResetDone, PasswordResetComplete,UserProfile
)
app_name = 'accounts'


urlpatterns =[
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/', UserPassReset.as_view(), name='reset'),
    path('reset/done/', PasswordResetDone.as_view(), name = 'password-reset-done'),
    path('confirm/<uidb64>/<token>/', PasswordConfirm.as_view(), name = 'password-confirm'),
    path('confirm/done/', PasswordResetComplete.as_view(), name = 'resaet-done'),
    path('userprofile/', UserProfile.as_view())
]

django_classbaseviews/first/urls.py
from django.urls import path
from . import views


app_name='first'

urlpatterns = [
    path('', views.Home.as_view(), name = 'home'),
    path('index/', views.Index.as_view(), name = 'index'),
    path('todo-list/', views.TodoListView.as_view(), name = 'todo-list'),
    path('todo-detail/<slug:myslug>', views.TodoDetailView.as_view(), name='todo-detail'),
    path('todo-create/>', views.TodoCreate.as_view(), name='todo-create'),
    path('todo-delete/<int:pk>/', views.TodoDelete.as_view(), name='todo-delete'),
    path('todo-update/<int:pk>/', views.TodoUpdate.as_view(), name='todo-update'),
    path('<int:year>/<int:month>/', views.MonthTodo.as_view(), name = 'month')<
]

django_classbaseviews/accounts/models.py
from django.db import models

# Create your models here.

django_classbaseviews/first/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Todo(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCAD)
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default=False)
    slug = models.SlugField(max_length=150)


    def __str__(self):
        return self.title
        
class Comment(models.Model):
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE, related_name='tcomments')
    name = models.CharField(max_length=200)
    body = models.TextField()

    def __str__(self):
        return self.name

django_classbaseviews/first/forms.py
from django import forms
from .models import Comment

class TodoCreateForm(forms.Form):
    title = forms.CharField(max_length=150)


class TodoCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('namme', 'body')
        

django_classbaseviews/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
# Create your views here.
from django.urls import reverse_lazy
from django.contrib.auth.views import (
        LoginView, LogoutView, PasswordResetView,
        PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
    )
from first.models import Todo

class UserLogin(LoginView):
    users = User.objects.all()
    extra_context = {'users':users}
    template_name = 'accounts/login.html'


class UserPassReset(PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('acccounts:password-reset-done')
    html_email_template_name = 'accounts/password_reset_email.html'


class PasswordResetDone(PasswordResetDoneView):
    template_name='accounts/reset_done.html'


class PasswordConfirm(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'


class UserProfile(generic.UpdateView):
    model = User
    template_name = 'polls/user.html'
    fields = ['first_name', 'last_name'] 

    def get_object(self):
        return User.objects.get(username= self.request.user.username)

django_classbaseviews/first/views.py
from django.shortcuts import render
from .models import Todo
# Create your views here.
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic import (
        ListView, DetailView, FormView,
        CreateView, UpdateView, DeleteView
    )
from .forms import TodoCreateForm, TodoCommentForm
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic.dates import MonthArchiveView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin



class Home(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'first/home.html')



class Index(TemplateView):
    template_name = 'first/todo_index.html'
    users = User.objects.all()
    extra_context = {'users':users}
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['todos'] = Todo.objects.all()
        return context

class TodoListView(ListView):
    template_name = 'first/todo_list.html' #first/todo_list.html
    model = Todo 
    '''
    queryset = Todo.objects.all() 
    ......or......
    def get_queryset(self):
        return Todo.objects.all().ordering('-created')
    '''    
    
    users = User.objects.all()
    extra_context = {'users':users}
    context_object_name = 'todos' #object_list


class TodoDetailView(LoginRequiredMixin, FormView, DetailView):
    model = Todo
    form_class = TodoCommentForm
    users = User.objects.all()
    extra_context = {'users':users}
    login_url = 'accounts:login'
    template_name = 'first/todo_detail.html' #first/todo_detal.html
    context_object_name = 'todo' #object

    def get_success_url(self): #back to the page for comment
        return reverse('first:todo-detail', kwargs={'pk':self.object.pk})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form =self.get_form() 
        if form.is_valid():
            comment = Comment(todo=self.object, name=form.cleaned_data['name'], body=form.cleaned_data['body'])
        return super().form_valid(form)
    '''
    querset = Todo.objects.filter(pulished=True)
    ......or......
    def get_queryset(self, **kwargs):
        if request.user.is_authenticated:
            return Todo.objects.filter(slug=self.kwargs['myslug'])
        else:
            pass

    --> path('<slug:myslug'/,...)
    
    >>>DEFINE WORKING WITH PK<<<

    slug_field = 'slug' #name in models
    slug_url_kwarg = 'myslug' #name in url
    '''


class TodoCreateForm(FormView):
    form_class = TodoCreateForm
    template_name = 'first/todo_create.html'
    success_url = reverse_lazy('first:home')
    
    def form_valid(self, form):
        self.create_todo(form=cleaned_data)
        return super().form_valid(form)

    def create_todo(sefl, data): #this def we created
        todo = Todo(title=data['title'], slug=slugify(data['title'], owner=self.request.user))
        todo.save()
        messages.success(self.request, 'your todo add', 'success')


class TodoCreate(CreateView):
    model = Todo
    fields = ('title',)
    template_name = 'first/todo_create.html'
    success_url = reverse_lazy('first:home')

    def form_valid(self, form):
        todo = form.save(commit=False)
        todo.slug = slugify(form.cleaned_data['title'])
        todo.owner = self.request.user
        messages.success(self.request, 'your todo add', 'success')
        return super().form_valid(form)


class TodoDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Todo
    template_name = 'first/todo_delete.html'
    success_url = reverse_lazy('first:home')

    def test_func(self):
        obj = self.get_object()
        obj.owner = self.request.user
        
class TodoUpdate(UpdateView):
    model = Todo
    fieds = ('title',)
    template_name = 'first/todo_update.html'
    success_url = reverse_lazy('first:home')


class MonthTodo(MonthArchiveView):
    model = Todo
    date_field = 'created'
    month_format = '%m'
    template_name = 'first/todo_month.html'

django_classbaseviews/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    {% for user in users %}
    <a> {{user.username}} </a>
    <hr>
    {% endfor %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="login" class="btn btn-primary">
    </form>
{% endblock %}

django_classbaseviews/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <p>password changed</p>
{% endblock %}

django_classbaseviews/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    {% if validlink %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="send">
    </form>
    {% else %}
    <p>no valid this link</p>
    {% endif %}
{% endblock %}

django_classbaseviews/accounts/templates/accounts/password_reset_email.html
this is for you yess for password change {{email}}
please click on link below

{{protocol}}//{{domain}}{% 'accounts:password-confirm' uidb64=uid token=token %}

django_classbaseviews/accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
    <p>password reset</p>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="send">
    </form>
{% endblock %}

django_classbaseviews/accounts/templates/accounts/reset_done.html
{% extends 'base.html' %}

{% block content %}
    <p>a link sent foer email, please click on thet link</p>
{% endblock %}

django_classbaseviews/first/templates/first/home.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

django_classbaseviews/first/templates/first/home_list.html
{% extends 'base.html' %}

{% block content %}
    {% for todo in todos %}
    <a href="{% url 'first:todo-detail' todo.pk %}"> {{todo.title}} </a>
    <hr>
    {% endfor %}
{% endblock %}

django_classbaseviews/first/templates/first/todo_create.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="create" class="btn btn-info">
    </form>
{% endblock %}

django_classbaseviews/first/templates/first/todo_delete.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <p>are you really {{ object.title }}</p>
    <input type="submit" value="delete" class="btn btn-danger">
</form>
{% endblock %}

django_classbaseviews/first/templates/first/todo_detail.html
{% extends 'base.html' %}

{% block content %}
{% for user in users %}
<a> {{user.username}} </a>
<hr>
{% endfor %}
    {{todo.title}}
    <a href="{% url 'first:todo-delete' todo.pk%}" class="btn btn-info">delete</a>
    <a href="{% url 'first:todo-update' todo.pk%}" class="btn btn-success">update</a>

    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="send" class="btn btn-primary">
    </form>
    <hr>
    {% for cmt in object.tcomments.all %}
        {{cmt.name}}
        {{cmt.body}}
    {% endfor %}
{% endblock %}

django_classbaseviews/first/templates/first/todo_index.html
{% extends 'base.html' %}

{% block content %}
    {% for todo in todos %}
       <a href="{% url 'first:todo-deatil' todo.pk %}"> {{todo.title}} </a>
       <hr>
    {% endfor %}
    {% for user in users %}
    <a "> {{user.username}} </a>
    <hr>
    {% endfor %}
{% endblock %}

django_classbaseviews/first/templates/first/todo_list.html
{% extends 'base.html' %}

{% block content %}

    {% for todo in todos %}
        <a href="{% url 'first:todo-detail' todo.pk %}">{{ todo.title }}</a>
    {% endfor %}  
    {% for user in users %}
    <a> {{user.username}} </a>
    <hr>
    {% endfor %}
{% endblock %}

django_classbaseviews/first/templates/first/todo_month.html
{% extends 'base.html' %}

{% block content %}
    {% for todo in object_list %}
        {{ todo.title }
    {% endfor %}
{% endblock %}

django_classbaseviews/first/templates/first/todo_update.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-info" value="update">
    </form>
{% endblock %}

django_classbaseviews/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% include 'inc/nav.html' %}
    <div class="jumbotron">
    {% include 'inc/messages.html' %}

    {% block content %} {% endblock %}
    </div>
</body>
</html>

django_classbaseviews/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg}}">{{msg}}</p>
    {% endfor %}
{% endif %}

django_classbaseviews/templates/inc/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="navbar-nav">
    <a class="nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
    {% if request.user.is_authenticated %}
      <a href="{% url 'accounts:logout' %}">logout</a>
    {% else %}
      <a href="{% url 'accounts:login' %}">login</a>
    {% endif %}
  
  </div>
</nav>